= Meditate Easy
Larndorfer Lukas, Harrucksteiner Jan, Vrhovac David
{docdate}
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

// print the toc here (not at the default position)
//toc::[]

== Pflichtenheft "Was mache ich"

=== Ausgangssituation
Immer mehr Menschen haben wegen Schule, Arbeit und Alltag viel Stress und versuchen deswegen zu meditieren um sich zu entspannen, aber es ist schwer eine gute App dafür zu finden. Deshalb wäre es sinnvoll eine einfache App zu entwickeln die gut erklärt wie Meditation funktioniert und viele verschiedene Übungen für Anfänger und auch für Fortgeschrittene anbietet.

=== Istzustand
Es gibt viele Meditationsapps auf dem Markt, aber diese Apps haben selten genaue Anleitungen für verschiedene Übungen und sind nicht sehr benutzerfreundlich. Die meisten bieten oft nur allgemeine Übungen, die sich nicht gut anpassen lassen (z.B. Dauer der Übung, Wiederholungen der Übung,...). Für viele Apps braucht man auch ständig eine Internetverbindung was sie unpraktisch macht wenn man unterwegs ist oder keine Internetverbindung hat.

=== Problemstellung

=== Aufgabenstellung

==== Funktionale Anforderungen

==== Nichtfunktionale Anforderungen (NFA)

=== Ziele

=== Mengengerüst
- Datenbewegungen: Übertragung von Meditationsanleitungen und -übungen
- Datenbestände: Meditationsanleitungen und -übungen
- Anzahl gleichzeitiger Benutzer: etwa 500 bis 1000 Benutzer

=== Rahmenbedingungen
- Projektzeitraum: Das Projekt soll zum Ende des Schuljahres abgeschlossen sein
- Technische Bedingungen: Entwicklung mit Java und JavaFX